language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
