language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
branches:
  only:
  - master
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - "npm run dev > /dev/null &"
